//--------------------------------------------------------------------------------------//
//
// Mendl's Bootstrap
// Created by Rafael Alvarez on January 21, 2025
// Abstract: Mendl's Bootstrap (boot.S) is the first thing that the hardware executes
// in the kernel. This sets up the Swift runtime environment by jumping to Kernel.swift
// 
//--------------------------------------------------------------------------------------//


